esphome:
  name: esp32

esp32:
  # Using nodemcu-32s and esp-idf fixes the compilation errors
  board: nodemcu-32s
  framework:
    type: esp-idf

logger:

api:

ota:
  - platform: esphome

wifi:
  # The double quotes here fix the apostrophe error
  ssid: "YOUR_WIFI_NAME"
  password: "YOUR_PASSWORD_NAME"

  ap:
    ssid: "Esp32 Fallback Hotspot"
    password: "YOUR_HOTSPOT_PASSWORD"

captive_portal:

# Your PIR Motion Sensor
binary_sensor:
  - platform: gpio
    pin: 27
    name: "Lab Motion Sensor"
    device_class: motion
